# Self-Exercise

In [1]:
#conda install numpy

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods
### There are lots of built-in ways to generate Arrays

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

Zeros and Ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Linespace: Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye: Creates an identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

rand: Create an array of the given shape and populate it with random samples from uniform distribution over [0,1).

In [20]:
np.random.rand(2)

array([0.65538682, 0.47326105])

In [21]:
np.random.rand(5,5)

array([[0.65873869, 0.81091511, 0.25075131, 0.40353846, 0.06440629],
       [0.86991927, 0.1237714 , 0.12413072, 0.50216841, 0.42433673],
       [0.35146358, 0.03142185, 0.61845773, 0.6113742 , 0.60769634],
       [0.67307789, 0.10739093, 0.95785815, 0.91203301, 0.01664216],
       [0.22778195, 0.93902576, 0.59235637, 0.39249852, 0.29850029]])

randn: Return a sample(or samples) from the "standard normal" distrubition. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([0.95056664, 0.8848346 ])

In [23]:
np.random.randn(5,5)

array([[-1.4803347 , -0.49952119,  0.47592652,  0.42762794,  1.16123293],
       [ 0.39435611, -0.7601295 ,  0.89850881, -0.5306987 , -1.50838752],
       [ 0.07277193, -0.25739948, -0.49319753,  0.04431974, -0.13241098],
       [ 0.66515055,  1.0404038 , -1.40900523,  0.5660121 , -1.42958891],
       [ 0.53946818,  0.10891285, -0.67035816, -2.29929981, -1.35557502]])

randint: Return random integers from low to high

In [24]:
np.random.randint(1,100)

94

In [25]:
np.random.randint(1,100,10)

array([14, 50, 35, 61,  5,  9, 23, 84, 19, 27])

# Array Attributes and Methods

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([ 7, 31, 17, 15,  4, 21,  2, 13, 45, 27])

Reshape: Returns an array containing the same data with a new shape.

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr

array([ 7, 31, 17, 15,  4, 21,  2, 13, 45, 27])

In [33]:
ranarr.max()

45

In [34]:
ranarr.argmax()

8

In [35]:
ranarr.min()

2

In [36]:
ranarr.argmin()

6

# Shape

In [39]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [43]:
arr.dtype

dtype('int32')

In [47]:
arr_2d = np.arange(50).reshape(5,10)

In [48]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])